// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi4etqO9pNSVBh3ZmdAscR5cJmAffiHdE',
    appId: '1:682618538356:web:080c99bf090ac6be99c421',
    messagingSenderId: '682618538356',
    projectId: 'crypto-wallet-af5b1',
    authDomain: 'crypto-wallet-af5b1.firebaseapp.com',
    storageBucket: 'crypto-wallet-af5b1.appspot.com',
    measurementId: 'G-7FR60RTW21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsG00q3moz_aZP3rx_tAWk8LaEbaXJLdU',
    appId: '1:682618538356:android:f5af24ec96e7355a99c421',
    messagingSenderId: '682618538356',
    projectId: 'crypto-wallet-af5b1',
    storageBucket: 'crypto-wallet-af5b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-VG7ukz54rdzjX2eOtk5f0gt1vELeBbE',
    appId: '1:682618538356:ios:863289358a39a2ad99c421',
    messagingSenderId: '682618538356',
    projectId: 'crypto-wallet-af5b1',
    storageBucket: 'crypto-wallet-af5b1.appspot.com',
    iosClientId:
        '682618538356-u3slauraqkk7g5ki937atpjc7tsar33k.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-VG7ukz54rdzjX2eOtk5f0gt1vELeBbE',
    appId: '1:682618538356:ios:863289358a39a2ad99c421',
    messagingSenderId: '682618538356',
    projectId: 'crypto-wallet-af5b1',
    storageBucket: 'crypto-wallet-af5b1.appspot.com',
    iosClientId:
        '682618538356-u3slauraqkk7g5ki937atpjc7tsar33k.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoWallet',
  );
}
